# Generated by Django 5.2.7 on 2025-11-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("USED", "Used"),
                ],
                default="BOOKED",
                max_length=10,
            ),
        ),
    ]
